export const activityCatalog = {
  rafting: {
    id: "rafting",
    name: "River Rafting",
    duration: "2.5 - 3 hrs",
    inclusions: "Guide, helmet, paddle, transport",
    basePrice: 1200,
    baseDemand: 64,
    weekendBoost: 12,
    seasonalPeakMonths: [3, 4, 5, 9, 10, 11],
    riskSensitivity: "high",
    totalSlotsWeekday: 60,
    totalSlotsWeekend: 90,
    vendorCount: 18,
    trustScore: 91,
    interests: ["adventure", "nature"],
  },
  bungee: {
    id: "bungee",
    name: "Bungee Jumping",
    duration: "1 hr slot",
    inclusions: "Safety briefing, harness, certificate",
    basePrice: 3500,
    baseDemand: 58,
    weekendBoost: 10,
    seasonalPeakMonths: [3, 4, 5, 9, 10, 11, 12],
    riskSensitivity: "high",
    totalSlotsWeekday: 36,
    totalSlotsWeekend: 48,
    vendorCount: 6,
    trustScore: 95,
    interests: ["adventure"],
  },
  camping: {
    id: "camping",
    name: "Riverside Camping",
    duration: "1 night",
    inclusions: "Tent stay, dinner, breakfast",
    basePrice: 2100,
    baseDemand: 52,
    weekendBoost: 16,
    seasonalPeakMonths: [2, 3, 4, 5, 9, 10, 11, 12],
    riskSensitivity: "medium",
    totalSlotsWeekday: 24,
    totalSlotsWeekend: 36,
    vendorCount: 14,
    trustScore: 87,
    interests: ["nature", "family", "spiritual"],
  },
  yoga: {
    id: "yoga",
    name: "Sunrise Yoga Session",
    duration: "90 mins",
    inclusions: "Instructor, yoga mat, herbal tea",
    basePrice: 850,
    baseDemand: 48,
    weekendBoost: 6,
    seasonalPeakMonths: [1, 2, 3, 10, 11, 12],
    riskSensitivity: "low",
    totalSlotsWeekday: 40,
    totalSlotsWeekend: 45,
    vendorCount: 22,
    trustScore: 94,
    interests: ["spiritual", "wellness"],
  },
  combo: {
    id: "combo",
    name: "Adventure Combo",
    duration: "Full day",
    inclusions: "Rafting + zipline + lunch",
    basePrice: 4900,
    baseDemand: 44,
    weekendBoost: 14,
    seasonalPeakMonths: [3, 4, 5, 9, 10, 11],
    riskSensitivity: "high",
    totalSlotsWeekday: 18,
    totalSlotsWeekend: 28,
    vendorCount: 9,
    trustScore: 89,
    interests: ["adventure", "nature"],
  },
};

export const plannerExperiences = [
  {
    id: "arrival-aarti",
    title: "Arrival + Triveni Ghat Ganga Aarti",
    interests: ["spiritual", "family", "budget"],
    cost: 400,
    vendorType: "guided local transfer",
    time: "Evening",
  },
  {
    id: "rafting-run",
    title: "16 km river rafting run",
    interests: ["adventure", "nature"],
    cost: 1200,
    vendorType: "rafting operator",
    time: "Morning",
  },
  {
    id: "bungee-jump",
    title: "Bungee jump experience",
    interests: ["adventure"],
    cost: 3500,
    vendorType: "bungee operator",
    time: "Midday",
  },
  {
    id: "cafe-hop",
    title: "Laxman Jhula cafe trail",
    interests: ["nature", "family", "budget"],
    cost: 650,
    vendorType: "cafe network",
    time: "Afternoon",
  },
  {
    id: "beatles-ashram",
    title: "Beatles Ashram + forest walk",
    interests: ["culture", "nature", "budget"],
    cost: 900,
    vendorType: "guided walk",
    time: "Morning",
  },
  {
    id: "yoga-class",
    title: "Sunrise yoga and sound healing",
    interests: ["spiritual", "wellness"],
    cost: 850,
    vendorType: "yoga studio",
    time: "Sunrise",
  },
  {
    id: "camping-night",
    title: "Riverside camping stay",
    interests: ["nature", "family", "adventure"],
    cost: 2100,
    vendorType: "camp operator",
    time: "Night",
  },
  {
    id: "waterfall-trip",
    title: "Neer Garh waterfall outing",
    interests: ["nature", "family", "budget"],
    cost: 500,
    vendorType: "local transport",
    time: "Morning",
  },
  {
    id: "temple-trail",
    title: "Temple trail + Ram Jhula walk",
    interests: ["spiritual", "culture", "budget"],
    cost: 300,
    vendorType: "self-guided",
    time: "Morning",
  },
  {
    id: "ayurveda-session",
    title: "Ayurveda therapy session",
    interests: ["wellness", "spiritual"],
    cost: 1800,
    vendorType: "wellness center",
    time: "Afternoon",
  },
];

export const stayBudgets = {
  low: { label: "Value stay", perNight: 1200 },
  mid: { label: "Comfort stay", perNight: 2200 },
  high: { label: "Boutique riverside stay", perNight: 4200 },
};

export const vendorSignals = {
  low: {
    emptySlotRisk: "High empty-slot risk",
    action: "Offer bundle discounts and push weekday inventory.",
  },
  medium: {
    emptySlotRisk: "Balanced demand",
    action: "Hold prices steady and promote verified packages.",
  },
  high: {
    emptySlotRisk: "Peak demand window",
    action: "Increase price cautiously and release backup slots.",
  },
};
